<?php

/**
 * Created by PhpStorm.
 * User: Stephen Nguyen
 * Date: 4/29/2017
 * Time: 11:41 AM
 */
class View extends \VatGia\Helpers\Facade
{

    public static function getFacadeAccessor()
    {
        return 'view';
    }

}

class Model extends \VatGia\Helpers\Facade
{
    public static function getFacadeAccessor()
    {
        return \VatGia\Model\ModelBase::class;
    }
}

class FacadeTest extends \PHPUnit\Framework\TestCase
{

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testAppContainerFacade()
    {
        //View::render($viewName = 'abc/test', []);
    }

    public function testFacadeFactory()
    {
        $model = Model::fields('abc');
        $this->assertInstanceOf(\VatGia\Model\ModelBase::class, $model);
    }

}