<?php
return [
    'sorting' => [
        [
            'field' => 'new',
            'label' => 'Mới nhất',
            'icon'  => 'icon-default',
        ],
        [
            'field' => 'top-sell',
            'label' => 'Bán chạy nhất',
            'icon'  => 'icon-top-sell',
        ],
        [
            'field' => 'top-commission',
            'label' => 'Hoa hồng lớn nhất',
            'icon'  => 'icon-top-commission',
        ],
        [
            'field' => 'last-minute',
            'label' => 'Phút chót',
            'icon'  => 'icon-last-minute',
        ],
        // [
        //     'field' => 'count-down',
        //     'label' => 'Đếm ngược',
        //     'icon'  => 'icon-count-down',
        // ],
    ],

    'sorting-shop' => [
        [
            'field' => 'new',
            'label' => 'Mới nhất',
            'icon'  => 'icon-default',
        ],
        [
            'field' => 'top-sell',
            'label' => 'Bán chạy',
            'icon'  => 'icon-top-sell',
        ],
    ],

    'sorting-cashback' => [
        [
            'field' => 'new',
            'label' => 'Mới nhất',
            'icon'  => 'icon-default',
        ],
        [
            'field' => 'top-sell',
            'label' => 'Bán chạy nhất',
            'icon'  => 'icon-top-sell',
        ],
        [
            'field' => 'top-commission',
            'label' => 'Tiền tặng lớn nhất',
            'icon'  => 'icon-top-commission',
        ],
        [
            'field' => 'last-minute',
            'label' => 'Sắp hêt ưu đãi',
            'icon'  => 'icon-last-minute',
        ],
    ],

    'array-bank' => [
        1=> 'VP BANK-NH Viet Nam Thinh Vuong',
        106=> 'BUSAN BANK-Busan Bank Co Ltd',
        104=> 'E.SUN BANK-E.SUN Commercial Bank Ltd',
        105=> 'SIAM COMMERCIAL BANK-NH The Siam Commercial Bank Public',
        4=> 'NHNN-NH Nha Nuoc',
        76=> 'KBNN-Kho bac nha nuoc',
        69=> 'CO-OP BANK-NH Hop Tac VN',
        23=> 'ABBANK-NH An Binh',
        14=> 'ACB-NH A Chau',
        8=> 'AGRIBANK-NHNo va PTNT VN',
        9=> 'BIDV-NH Dau Tu va Phat Trien VN',
        41=> 'BAOVIETBANK-NH Bao Viet',
        16=> 'DONG A BANK-NH Dong A',
        15=> 'DAIABANK-NH Dai A',
        30=> 'EXIMBANK-NH Xuat nhap khau',
        24=> 'VIETCAPITALBANK-NH Ban Viet Gia Dinh',
        26=> 'GPBANK-NH Dau khi toan cau',
        13=> 'HDBANK-NH TMCP Phat trien TP HCM',
        42=> 'KIENLONGBANK-NH Kien Long',
        39=> 'LIENVIETPOSTBANK-NH Buu dien Lien Viet',
        29=> 'MARITIME BANK-NH Hang Hai',
        25=> 'MB-NH Quan Doi',
        22=> 'MDB-NH Phat Trien Me Kong',
        7=> 'MHB-NH phat trien nha DBSCL',
        17=> 'NAM A BANK-NH Nam A',
        18=> 'BAC A BANK-NH Bac A',
        33=> 'NAVIBANK-NH Nam Viet',
        32=> 'OCB-NH Phuong Dong',
        21=> 'OCEANBANK-NH Dai Duong',
        27=> 'PGBANK-NH Xang dau Petrolimex',
        44=> 'SACOMBANK-NH Sai Gon Thuong Tin',
        47=> 'SAIGONBANK-NH Sai Gon Cong Thuong',
        45=> 'SCB-NH TMCP Sai Gon',
        20=> 'SEABANK-NH Dong Nam A',
        46=> 'SHB-NH Sai Gon Ha Noi',
        31=> 'SOUTHERN BANK-NH Phuong Nam',
        28=> 'TECHCOMBANK-NH Ky Thuong',
        40=> 'TPBANK-NH Tien Phong',
        35=> 'VNCB-NH Xay Dung VN',
        19=> 'VIET A BANK-NH Viet A',
        5=> 'VBSP-NH Chinh sach Xa Hoi',
        6=> 'VDB-NH Phat trien Viet Nam',
        34=> 'VIB-NH Quoc Te',
        37=> 'VIET BANK-NH Viet Nam Thuong Tin',
        11=> 'VIETCOMBANK-NH Ngoai Thuong',
        10=> 'VIETINBANK-NH Cong Thuong',
        38=> 'PVCOMBANK-NH Dai Chung',
        48=> 'VID-NH VID Public',
        49=> 'IVB-NH Indovina',
        52=> 'VRB-NH Lien doanh Viet Nga',
        51=> 'VINASIAM-NH Lien doanh Viet Thai',
        70=> 'LVB-NH lien doanh Viet Lao',
        71=> 'BIDC-NH Dau Tu va PT Campuchia',
        53=> 'ANZ-NH ANZ Viet Nam',
        59=> 'BANGKOK BANK-Bangkok Bank',
        78=> 'BOC-Bank of China',
        79=> 'BOComm-Bank of Communication',
        63=> 'BTMU-Bank of Tokyo Mitsubishi',
        80=> 'BNP-PARIBAS',
        81=> 'CATHAY BANK-Cathay Bank',
        56=> 'CHIFONBANK-NH Chifon Dai Loan',
        82=> 'CCB-China Construction Bank',
        77=> 'CTBC Bank-Chinatrust Commercial Bank',
        55=> 'CITIBANK-CitiBank Viet Nam',
        62=> 'COMMONWEALTH-Commonwealth Bank',
        84=> 'DBS-DBS Bank Ltd',
        72=> 'DEUTSCHE BANK-Deutsche Bank Viet Nam',
        85=> 'SINOPAC-Far East National Bank',
        86=> 'FCB-First Commercial Bank',
        68=> 'HLB-Hong Leong Bank ',
        61=> 'HSBC-HSBC Viet Nam',
        87=> 'HNCB-Hua Nan Commerecial Bank',
        88=> 'ICBC-NH Cong Thuong Trung Quoc',
        89=> 'IBK-Industrial Bank Of Korea',
        90=> 'JP MORGAN CHASE-JP Morgan Chase Bank',
        91=> 'KOOKMIN BANK-Kookmin Bank',
        92=> 'KEB Hana Bank-Korea Exchange Bank',
        93=> 'MALAYAN BANKING BERHAD-Malayan Banking Berhad',
        57=> 'MAY BANK-May Bank',
        94=> 'MEGA ICBC-Mega ICBC',
        60=> 'MIZUHO-Mizuho Corporate Bank, Ltd',
        95=> 'BPCE IOM-BPCE International et Outre-Mer',
        65=> 'CREDIT AGRICOLE-Credit Agricole CIB',
        97=> 'OCBC-Oversea Chinese Banking Corp',
        73=> 'Shinhan Vietnam Bank Limited',
        54=> 'STANDARD CHARTERED-Standard Chartered Viet Nam',
        67=> 'SMBC-Sumitomo Mitsui Bank',
        50=> 'SHINHAN-NH ShinhanVina',
        98=> 'TAIPEI FUBON-Taipei Fubon Bank',
        99=> 'SCSB-Shanghai Commercial &amp; Savings',
        100=> 'UOB-United Overseas Bank',
        64=> 'WOORI BANK-Woori Bank',
        102=> 'NCB-NH Quoc Dan',
        103=> 'KEB Hana Bank HCM-Korean Exchange Bank HCM',
    ],
];